apiVersion: v1
kind: ServiceAccount
metadata:
  name: rag-service-account
  namespace: rag-backend
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rag-service-account
  namespace: rag-vector-store
