apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-ui
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "rag-frontend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: rag-ui
  template:
    metadata:
      labels:
        app: rag-ui
    spec:
      containers:
        - name: rag-frontend
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: REACT_APP_API_URL
              value: {{ .Values.mainBackendUrl | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
