apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: employee-attrition
  namespace: default
spec:
  predictor:
    containers:
      - name: kserve-container
        image: techiescamp/attrition-inference:1.0.0
        ports:
          - containerPort: 8080
            protocol: TCP
        resources:
          requests:
            cpu: "200m"
            memory: "512Mi"
          limits:
            cpu: "1"
            memory: "1Gi"