apiVersion: v1
kind: ConfigMap
metadata:
  name: sync-env
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "rag-backend.labels" . | nindent 4 }}
data:
  AWS_REGION: {{ .Values.config.awsRegion | quote }}
  BEDROCK_EMBEDDING_MODEL_ID: {{ .Values.config.bedrockEmbeddingModel | quote }}
  K8_REPO_URL: {{ .Values.config.k8RepoUrl | quote }}
  VECTOR_DB_URL: {{ .Values.config.vectorDbUrl | quote }}
