apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-ui
  namespace: rag-frontend
  labels:
    app: rag-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag-ui
  template:
    metadata:
      labels:
        app: rag-ui
    spec:
      containers:
      - name: rag-frontend
        image: catninjauser/ragfrontend:1.0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: REACT_APP_API_URL
          value: "http://rag-backend-service.rag-backend.svc.cluster.local:8000"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
