namespace: rag-vector-store

serviceAccount:
  name: rag-service-account

image:
  repository: catninjauser/regpvector
  tag: "1.0.1"
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  port: 8001

resources:
  requests:
    cpu: "200m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

config:
  awsRegion: "us-west-2"
  awsAccountId: "637423664276"
  bedrockEmbeddingModel: "amazon.titan-embed-text-v2:0"
  s3VectorBucketName: "vector-bucket-demo"
  s3VectorIndexName: "vector-bucket-index"
