apiVersion: batch/v1
kind: CronJob
metadata:
  name: sync-backend
  namespace: rag-backend
spec:
  schedule: "0 0 * * *"
  timeZone: Asia/Kolkata
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: sync-backend
        spec:
          serviceAccountName: rag-service-account
          restartPolicy: OnFailure
          containers:
            - name: sync-backend
              image: catninjauser/ragsync:1.0.0
              imagePullPolicy: IfNotPresent
              envFrom:
                - configMapRef:
                    name: sync-env
              resources:
                requests:
                  cpu: "200m"
                  memory: "256Mi"
                limits:
                  cpu: "500m"
                  memory: "512Mi"
