apiVersion: apps/v1
kind: Deployment
metadata:
  name: vector-store
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "rag-vector-store.labels" . | nindent 4 }}
    app: vector-store
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: vector-store
  template:
    metadata:
      labels:
        app: vector-store
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: vector-store
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          envFrom:
            - configMapRef:
                name: vector-store-env
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
